//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.nationaalarchief.nl/RIP/v0.3")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.nationaalarchief.nl/RIP/v0.3", IsNullable=false)]
public partial class recordInformationPackage 
{
    
    private packageHeaderType packageHeaderField;
    
    private List <ripRecordType> recordField;
    
    /// <remarks/>
    public packageHeaderType packageHeader {
        get {
            return this.packageHeaderField;
        }
        set {
            this.packageHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("record")]
    public List<ripRecordType> record {
        get {
            return this.recordField;
        }
        set {
            this.recordField = value;
        }
    }

    public IEnumerator GetEnumerator()
    {
        throw new System.NotImplementedException();
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/RIP/v0.3")]
public partial class packageHeaderType {
    
    private string identificatieField;
    
    private System.DateTime datumField;
    
    private string[] omschrijvingField;
    
    private string bronField;
    
    private string doelField;
    
    /// <remarks/>
    public string identificatie {
        get {
            return this.identificatieField;
        }
        set {
            this.identificatieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("omschrijving")]
    public string[] omschrijving {
        get {
            return this.omschrijvingField;
        }
        set {
            this.omschrijvingField = value;
        }
    }
    
    /// <remarks/>
    public string bron {
        get {
            return this.bronField;
        }
        set {
            this.bronField = value;
        }
    }
    
    /// <remarks/>
    public string doel {
        get {
            return this.doelField;
        }
        set {
            this.doelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/RIP/v0.3")]
public partial class ripMetadataType {
    
    private System.Xml.XmlElement[] anyField;
    
    private string schemaURIField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string schemaURI {
        get {
            return this.schemaURIField;
        }
        set {
            this.schemaURIField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/RIP/v0.3")]
public partial class ripRecordHeaderType {
    
    private string identificatieField;
    
    private string[] omschrijvingField;
    
    private ripRecordStatusType statusField;
    
    public ripRecordHeaderType() {
        this.statusField = ripRecordStatusType.nieuw;
    }
    
    /// <remarks/>
    public string identificatie {
        get {
            return this.identificatieField;
        }
        set {
            this.identificatieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("omschrijving")]
    public string[] omschrijving {
        get {
            return this.omschrijvingField;
        }
        set {
            this.omschrijvingField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(ripRecordStatusType.nieuw)]
    public ripRecordStatusType status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/RIP/v0.3")]
public enum ripRecordStatusType {
    
    /// <remarks/>
    nieuw,
    
    /// <remarks/>
    gewijzigd,
    
    /// <remarks/>
    verwijderd,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nationaalarchief.nl/RIP/v0.3")]
public partial class ripRecordType {
    
    private ripRecordHeaderType recordHeaderField;
    
    private ripMetadataType[] metadataField;
    
    /// <remarks/>
    public ripRecordHeaderType recordHeader {
        get {
            return this.recordHeaderField;
        }
        set {
            this.recordHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("metadata")]
    public ripMetadataType[] metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
}
