//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Topx.FileAnalysis.Models
{
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.nationalarchives.gov.uk/pronom/SignatureFile")]
    [XmlRoot(Namespace="http://www.nationalarchives.gov.uk/pronom/SignatureFile", IsNullable=false)]
    public partial class FFSignatureFile {
    
        private FFSignatureFileInternalSignature[] internalSignatureCollectionField;
    
        private FFSignatureFileFileFormat[] fileFormatCollectionField;
    
        private System.DateTime dateCreatedField;
    
        private byte versionField;
    
        /// <remarks/>
        [XmlArrayItem("InternalSignature", IsNullable=false)]
        public FFSignatureFileInternalSignature[] InternalSignatureCollection {
            get {
                return this.internalSignatureCollectionField;
            }
            set {
                this.internalSignatureCollectionField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem("FileFormat", IsNullable=false)]
        public FFSignatureFileFileFormat[] FileFormatCollection {
            get {
                return this.fileFormatCollectionField;
            }
            set {
                this.fileFormatCollectionField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public byte Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.nationalarchives.gov.uk/pronom/SignatureFile")]
    public partial class FFSignatureFileInternalSignature {
    
        private FFSignatureFileInternalSignatureByteSequence[] byteSequenceField;
    
        private ushort idField;
    
        private string specificityField;
    
        /// <remarks/>
        [XmlElement("ByteSequence")]
        public FFSignatureFileInternalSignatureByteSequence[] ByteSequence {
            get {
                return this.byteSequenceField;
            }
            set {
                this.byteSequenceField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public ushort ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string Specificity {
            get {
                return this.specificityField;
            }
            set {
                this.specificityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.nationalarchives.gov.uk/pronom/SignatureFile")]
    public partial class FFSignatureFileInternalSignatureByteSequence {
    
        private FFSignatureFileInternalSignatureByteSequenceSubSequence[] subSequenceField;
    
        private string referenceField;
    
        private string endiannessField;
    
        /// <remarks/>
        [XmlElement("SubSequence")]
        public FFSignatureFileInternalSignatureByteSequenceSubSequence[] SubSequence {
            get {
                return this.subSequenceField;
            }
            set {
                this.subSequenceField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string Endianness {
            get {
                return this.endiannessField;
            }
            set {
                this.endiannessField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.nationalarchives.gov.uk/pronom/SignatureFile")]
    public partial class FFSignatureFileInternalSignatureByteSequenceSubSequence {
    
        private object[] itemsField;
    
        private ushort minFragLengthField;
    
        private byte positionField;
    
        private uint subSeqMaxOffsetField;
    
        private bool subSeqMaxOffsetFieldSpecified;
    
        private ushort subSeqMinOffsetField;
    
        private bool subSeqMinOffsetFieldSpecified;
    
        /// <remarks/>
        [XmlElement("DefaultShift", typeof(short))]
        [XmlElement("LeftFragment", typeof(FFSignatureFileInternalSignatureByteSequenceSubSequenceLeftFragment))]
        [XmlElement("RightFragment", typeof(FFSignatureFileInternalSignatureByteSequenceSubSequenceRightFragment))]
        [XmlElement("Sequence", typeof(string))]
        [XmlElement("Shift", typeof(FFSignatureFileInternalSignatureByteSequenceSubSequenceShift))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public ushort MinFragLength {
            get {
                return this.minFragLengthField;
            }
            set {
                this.minFragLengthField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public byte Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public uint SubSeqMaxOffset {
            get {
                return this.subSeqMaxOffsetField;
            }
            set {
                this.subSeqMaxOffsetField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool SubSeqMaxOffsetSpecified {
            get {
                return this.subSeqMaxOffsetFieldSpecified;
            }
            set {
                this.subSeqMaxOffsetFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public ushort SubSeqMinOffset {
            get {
                return this.subSeqMinOffsetField;
            }
            set {
                this.subSeqMinOffsetField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool SubSeqMinOffsetSpecified {
            get {
                return this.subSeqMinOffsetFieldSpecified;
            }
            set {
                this.subSeqMinOffsetFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.nationalarchives.gov.uk/pronom/SignatureFile")]
    public partial class FFSignatureFileInternalSignatureByteSequenceSubSequenceLeftFragment {
    
        private uint maxOffsetField;
    
        private ushort minOffsetField;
    
        private byte positionField;
    
        private string valueField;
    
        /// <remarks/>
        [XmlAttribute()]
        public uint MaxOffset {
            get {
                return this.maxOffsetField;
            }
            set {
                this.maxOffsetField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public ushort MinOffset {
            get {
                return this.minOffsetField;
            }
            set {
                this.minOffsetField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public byte Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.nationalarchives.gov.uk/pronom/SignatureFile")]
    public partial class FFSignatureFileInternalSignatureByteSequenceSubSequenceRightFragment {
    
        private uint maxOffsetField;
    
        private ushort minOffsetField;
    
        private byte positionField;
    
        private string valueField;
    
        /// <remarks/>
        [XmlAttribute()]
        public uint MaxOffset {
            get {
                return this.maxOffsetField;
            }
            set {
                this.maxOffsetField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public ushort MinOffset {
            get {
                return this.minOffsetField;
            }
            set {
                this.minOffsetField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public byte Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.nationalarchives.gov.uk/pronom/SignatureFile")]
    public partial class FFSignatureFileInternalSignatureByteSequenceSubSequenceShift {
    
        private string byteField;
    
        private short valueField;
    
        /// <remarks/>
        [XmlAttribute()]
        public string Byte {
            get {
                return this.byteField;
            }
            set {
                this.byteField = value;
            }
        }
    
        /// <remarks/>
        [XmlText()]
        public short Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.nationalarchives.gov.uk/pronom/SignatureFile")]
    public partial class FFSignatureFileFileFormat {
    
        private ushort[] internalSignatureIDField;
    
        private string[] extensionField;
    
        private ushort[] hasPriorityOverFileFormatIDField;
    
        private ushort idField;
    
        private string mIMETypeField;
    
        private string nameField;
    
        private string pUIDField;
    
        private string versionField;
    
        /// <remarks/>
        [XmlElement("InternalSignatureID")]
        public ushort[] InternalSignatureID {
            get {
                return this.internalSignatureIDField;
            }
            set {
                this.internalSignatureIDField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Extension")]
        public string[] Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("HasPriorityOverFileFormatID")]
        public ushort[] HasPriorityOverFileFormatID {
            get {
                return this.hasPriorityOverFileFormatIDField;
            }
            set {
                this.hasPriorityOverFileFormatIDField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public ushort ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string MIMEType {
            get {
                return this.mIMETypeField;
            }
            set {
                this.mIMETypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string PUID {
            get {
                return this.pUIDField;
            }
            set {
                this.pUIDField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
}