//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topx.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestand
    {
        public System.Guid Id { get; set; }
        public string Dossier_IdentificatieKenmerk { get; set; }
        public string Naam { get; set; }
        public string Relatie_RelatieId { get; set; }
        public string Relatie_TypeRelatie { get; set; }
        public string Relatie_DatumOfPperiode { get; set; }
        public string Vorm_RedactieGenre { get; set; }
        public string Formaat_IdentificatieKenmerk { get; set; }
        public string Formaat_Bestandsnaam_Naam { get; set; }
        public string Formaat_Bestandsnaam_Extentie { get; set; }
        public Nullable<long> Formaat_Omvang { get; set; }
        public string Formaat_Bestandsformaat { get; set; }
        public string Formaat_FysiekeIntegriteit_Algoritme { get; set; }
        public string Formaat_FysiekeIntegriteit_Waarde { get; set; }
        public string Formaat_FysiekeIntegriteit_DatumEnTijd { get; set; }
        public string Formaat_DatumAanmaak { get; set; }
    }
}
