//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topx.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dossier
    {
        public long Id { get; set; }
        public string IdentificatieKenmerk { get; set; }
        public string Naam { get; set; }
        public string Classificatie_Code { get; set; }
        public string Classificatie_Omschrijving { get; set; }
        public string Classificatie_Bron { get; set; }
        public string Classificatie_DatumOfPeriode { get; set; }
        public string Dekking_InTijd_Begin { get; set; }
        public string Dekking_InTijd_Eind { get; set; }
        public string Dekking_GeografischGebied { get; set; }
        public string Taal { get; set; }
        public string Eventgeschiedenis_DatumOfPeriode { get; set; }
        public string Eventgeschiedenis_Type { get; set; }
        public string Eventgeschiedenis_VerantwoordelijkeFunctionaris { get; set; }
        public string Eventplan_DatumOfPeriode { get; set; }
        public string Eventplan_DatumOfPeriode_Type { get; set; }
        public string Eventplan_Aanleiding { get; set; }
        public string Eventplan_Beschrijving { get; set; }
        public string Relatie_Id { get; set; }
        public string Relatie_Type { get; set; }
        public string Relatie_DatumOfPeriode { get; set; }
        public string Context_Actor_IdentificatieKenmerk { get; set; }
        public string Context_Actor_AggregatieNiveau { get; set; }
        public string Context_Actor_GeautoriseerdeNaam { get; set; }
        public string Context_Activiteit_Naam { get; set; }
        public string Gebruiksrechten_OmschrijvingVoorwaarden { get; set; }
        public string Gebruiksrechten_DatumOfPeriode { get; set; }
        public string Vertrouwelijkheid_ClassificatieNiveau { get; set; }
        public string Vertrouwelijkheid_DatumOfPeriode { get; set; }
        public string Openbaarheid_OmschrijvingBeperkingen { get; set; }
        public string Openbaarheid_DatumOfPeriode { get; set; }
        public string Integriteit { get; set; }
    }
}
