//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topx.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldMappings
    {
        public int Id { get; set; }
        public string DatabaseFieldName { get; set; }
        public string MappedFieldName { get; set; }
    }
}
