//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topx.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOPX_GenericEntities : DbContext
    {
        public TOPX_GenericEntities()
            : base("name=TOPX_GenericEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bestand> Bestand { get; set; }
        public virtual DbSet<Dossier> Dossier { get; set; }
        public virtual DbSet<FieldMapping> FieldMapping { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<Log> Log { get; set; }
    }
}
