// <auto-generated />
namespace Topx.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TMLO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TMLO));
        
        string IMigrationMetadata.Id
        {
            get { return "201901221608418_TMLO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
