//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class checksum
    {
        public string Checksum1 { get; set; }
        public string Filename { get; set; }
        public string FilenameClean { get; set; }
        public System.Guid Id { get; set; }
    }
}
