//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EersteShift
    {
        public string Bestand { get; set; }
        public string Column_1 { get; set; }
        public string Column_2 { get; set; }
        public string Column_3 { get; set; }
        public string Column_4 { get; set; }
        public string Column_5 { get; set; }
        public string Column_6 { get; set; }
        public string Column_7 { get; set; }
        public string Column_8 { get; set; }
        public string Column_9 { get; set; }
        public string Column_10 { get; set; }
        public string Column_11 { get; set; }
        public string Column_12 { get; set; }
        public string Column_13 { get; set; }
        public string Column_14 { get; set; }
        public string Column_15 { get; set; }
        public string Column_16 { get; set; }
        public string Column_17 { get; set; }
        public string Column_18 { get; set; }
        public string Column_19 { get; set; }
        public string Column_20 { get; set; }
        public string Column_21 { get; set; }
        public string Column_22 { get; set; }
        public string Column_23 { get; set; }
        public string Column_24 { get; set; }
        public string Column_25 { get; set; }
        public string Column_26 { get; set; }
        public string Column_27 { get; set; }
        public string Column_28 { get; set; }
        public string Column_29 { get; set; }
        public string Column_30 { get; set; }
        public string Column_31 { get; set; }
        public string Column_32 { get; set; }
        public string Column_33 { get; set; }
        public string Column_34 { get; set; }
        public string Column_35 { get; set; }
        public string Column_36 { get; set; }
        public string Column_37 { get; set; }
        public string Column_38 { get; set; }
        public string Column_39 { get; set; }
        public string Column_40 { get; set; }
        public string Column_41 { get; set; }
        public string Column_42 { get; set; }
        public string Column_43 { get; set; }
        public string Column_44 { get; set; }
        public string Column_45 { get; set; }
        public string Column_46 { get; set; }
    }
}
