//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSizes
    {
        public string Bestandsnaam { get; set; }
        public string Omvang_Byte__B_ { get; set; }
        public string Type { get; set; }
        public string Gemaakt_op { get; set; }
        public string Gewijzigd_op { get; set; }
        public string Toegestaan_op { get; set; }
        public string Bevat_map { get; set; }
        public string CleanName { get; set; }
        public System.Guid Id { get; set; }
    }
}
