//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOPXEntities : DbContext
    {
        public TOPXEntities()
            : base("name=TOPXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Source> Source { get; set; }
        public virtual DbSet<FileSizes> FileSizes { get; set; }
        public virtual DbSet<Openbaarheid> Openbaarheid { get; set; }
        public virtual DbSet<Gebruiksrechten> Gebruiksrechten { get; set; }
        public virtual DbSet<TestSet> TestSet { get; set; }
        public virtual DbSet<checksum> checksum { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<MarkedAsDelivered> MarkedAsDelivered { get; set; }
        public virtual DbSet<Source_temp> Source_temp { get; set; }
        public virtual DbSet<EersteShift> EersteShift { get; set; }
        public virtual DbSet<DossiersZonderBeschikking> DossiersZonderBeschikking { get; set; }
    }
}
