//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Openbaarheid
    {
        public long Id { get; set; }
        public string naam { get; set; }
        public string omschrijvingBeperkingen { get; set; }
        public Nullable<System.DateTime> begin { get; set; }
        public Nullable<System.DateTime> eind { get; set; }
    }
}
