//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public int Id { get; set; }
        public string C2_dn_Bestand { get; set; }
        public string Bouwvergnr2 { get; set; }
        public string Straat { get; set; }
        public string Postcode { get; set; }
        public string AdresFull { get; set; }
        public string Adres { get; set; }
        public string Huisnr { get; set; }
        public string Voorvoegsl { get; set; }
        public string StraatHuisnr { get; set; }
        public string Postcode2 { get; set; }
        public string Bvnr { get; set; }
        public string Jaar { get; set; }
        public string C2zn__Zaaknummer { get; set; }
        public string C19_1_DN_Tabnaam { get; set; }
        public string C4_dn_Omschrijving { get; set; }
        public string C91_zn_Datum_vergunning { get; set; }
        public string C4_zn_Omschrijving { get; set; }
        public string OmschrijvingCompleet { get; set; }
        public string Plaatsnaam { get; set; }
        public string C15c_Gemeente { get; set; }
        public string C51zn_classificatiecode { get; set; }
        public string C52zn_Omschrijving_classificatiecode_ { get; set; }
        public string C53_zn_Bron_ { get; set; }
        public string Omschrijving_ { get; set; }
        public string Gemeentecode { get; set; }
        public string C54_zn_Bron_classificatiecode { get; set; }
        public string KvK_nummer { get; set; }
        public string Omvang_in_MB { get; set; }
        public string Bestandsformaat { get; set; }
        public string Language { get; set; }
        public string Datum_vergunning { get; set; }
        public string C_Bouw_en_woningtoezicht { get; set; }
        public string zn_bn_Hierarchisch { get; set; }
        public string Gemeente { get; set; }
        public string Organisatie { get; set; }
        public string Verlenen_bouwvergunningen { get; set; }
        public string Vrij_te_gebruiken { get; set; }
        public string Openbaar { get; set; }
        public string C_Integer { get; set; }
        public string Enkelvoudig { get; set; }
        public string Aanmaakdatum_bestand { get; set; }
        public string C_Aggregatieniveau { get; set; }
        public string C_Relatie_ID { get; set; }
        public string Checksum { get; set; }
        public string Datum { get; set; }
        public string C_BN_Algoritme { get; set; }
        public string ZN_DN_Classificatie { get; set; }
        public string Column_47 { get; set; }
        public string Datum_vergunning2 { get; set; }
        public string Zaaknummer { get; set; }
        public string BN_Bestand { get; set; }
        public string C21_BN__Bestand { get; set; }
        public Nullable<long> FileSize_Bytes { get; set; }
    }
}
